version: "3.9"

services:
  app:
    build: .
    depends_on:
      - db
    volumes:
      - .:/app
      - ./node_modules:/app/node_modules/
    ports:
      - "3000:3000"
    command: npm run start:dev

  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: decks_and_cards
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
